# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\mubu_login_create_doc.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubuLoginCreateDoc(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/login")
            .get("https://mubu.com/login")
            .with_headers(
                **{
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "document",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-user": "?1",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1610268759",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1610244987",
                    "SESSION": "f4257d1a-bb99-4b96-9680-e5c6642eaf70",
                    "SLARDAR_WEB_ID": "627a324d-1525-4012-a443-4dd5a38741f6",
                    "_ga": "GA1.2.1478645020.1610244987",
                    "_gat": "1",
                    "_gat_UA-77727571-3": "1",
                    "_gid": "GA1.2.2087299800.1610244987",
                    "country": "US",
                    "csrf_token": "3f8a84d5-05b1-4568-b776-332e1c64ce18",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "data_unique_id": "14a656ae-aec4-4715-8e5b-cead72d29520",
                    "language": "en-US",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_focusId": "987897cf-710c-4420-8f19-176eb7f41d3",
                    "reg_from": "https%3A%2F%2Fwww.google.com.hk%2F",
                    "reg_prepareId": "176eb7f3d8a-176eb7f3d7a-4420-8f19-27d891871473",
                    "use-redesign": "1",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login/password")
            .get("https://mubu.com/login/password")
            .with_headers(
                **{
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "referer": "https://mubu.com/login",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "document",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-user": "?1",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1610268763",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1610244987",
                    "SESSION": "f4257d1a-bb99-4b96-9680-e5c6642eaf70",
                    "SLARDAR_WEB_ID": "2cca9f4b-9ef6-4ee5-a0aa-0a2f29d876ae",
                    "_ga": "GA1.2.1478645020.1610244987",
                    "_gat": "1",
                    "_gat_UA-77727571-3": "1",
                    "_gid": "GA1.2.2087299800.1610244987",
                    "country": "US",
                    "csrf_token": "3f8a84d5-05b1-4568-b776-332e1c64ce18",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "data_unique_id": "14a656ae-aec4-4715-8e5b-cead72d29520",
                    "language": "en-US",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_focusId": "7ce9b7ae-6352-4acb-af0f-176eb7f6403",
                    "reg_from": "https%3A%2F%2Fwww.google.com.hk%2F",
                    "reg_prepareId": "176eb7f62f6-176eb7f625b-4acb-af0f-976a9096745c",
                    "use-redesign": "1",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/login/submit")
            .post("https://mubu.com/api/login/submit")
            .with_headers(
                **{
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "47",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/login/password",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-origin",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "x-requested-with": "XMLHttpRequest",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1610268765",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1610244987",
                    "SESSION": "f4257d1a-bb99-4b96-9680-e5c6642eaf70",
                    "SLARDAR_WEB_ID": "c21176ef-c55b-4160-9a14-f6078e77132e",
                    "_ga": "GA1.2.1478645020.1610244987",
                    "_gat": "1",
                    "_gid": "GA1.2.2087299800.1610244987",
                    "country": "US",
                    "csrf_token": "3f8a84d5-05b1-4568-b776-332e1c64ce18",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "data_unique_id": "14a656ae-aec4-4715-8e5b-cead72d29520",
                    "language": "en-US",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_focusId": "7ce9b7ae-6352-4acb-af0f-176eb7f6403",
                    "reg_from": "https%3A%2F%2Fwww.google.com.hk%2F",
                    "reg_prepareId": "176eb7f62f6-176eb7f625b-4acb-af0f-976a9096745c",
                    "use-redesign": "1",
                }
            )
            .with_data(
                {"password": "1220jj", "phone": "17625416583", "remember": "true"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/app")
            .get("https://mubu.com/app")
            .with_headers(
                **{
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "referer": "https://mubu.com/login/password",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "document",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-user": "?1",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1610268765",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1610244987",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "SESSION": "f4257d1a-bb99-4b96-9680-e5c6642eaf70",
                    "SLARDAR_WEB_ID": "c21176ef-c55b-4160-9a14-f6078e77132e",
                    "_ga": "GA1.2.1478645020.1610244987",
                    "_gat": "1",
                    "_gid": "GA1.2.2087299800.1610244987",
                    "country": "US",
                    "csrf_token": "3f8a84d5-05b1-4568-b776-332e1c64ce18",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "data_unique_id": "14a656ae-aec4-4715-8e5b-cead72d29520",
                    "language": "en-US",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_focusId": "7ce9b7ae-6352-4acb-af0f-176eb7f6403",
                    "reg_from": "https%3A%2F%2Fwww.google.com.hk%2F",
                    "reg_prepareId": "176eb7f62f6-176eb7f625b-4acb-af0f-976a9096745c",
                    "use-redesign": "1",
                    "user_persistence": "fb76fe60-4f34-463b-8e58-76ad1c09d90f",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/")
            .get("https://api2.mubu.com/v3/")
            .with_headers(
                **{
                    "accept": "image/avif,image/webp,image/apng,image/*,*/*;q=0.8",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "image",
                    "sec-fetch-mode": "no-cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1610268765",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1610244987",
                    "SLARDAR_WEB_ID": "c21176ef-c55b-4160-9a14-f6078e77132e",
                    "_ga": "GA1.2.1478645020.1610244987",
                    "_gat": "1",
                    "_gat_UA-77727571-3": "1",
                    "_gid": "GA1.2.2087299800.1610244987",
                    "use-redesign": "1",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 17)
            .assert_equal("body.msg", "illegal request")
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
            .post("https://api2.mubu.com/v3/api/message/get_message_unread")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "10",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "7b2b0c37-d557-4a97-9a5d-349cf9aafd2e",
                }
            )
            .with_json({"page": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get_all_documents_page")
            .post("https://api2.mubu.com/v3/api/list/get_all_documents_page")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "12",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "d7ddc04c-46af-4e8a-9950-76944ea5da90",
                }
            )
            .with_json({"start": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("https://api2.mubu.com/v3/api/user/profile")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "0",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "dd6de712-4220-457f-87b8-36019e3cc360",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/star_relation/get")
            .get("https://api2.mubu.com/v3/api/list/star_relation/get")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "afe5d7fe-5779-42db-a9da-2e7bf35f5530",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "30",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "37ca5869-a410-4fa9-89a4-e0fbdd084545",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("https://api2.mubu.com/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "0",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "34d411c5-32bc-419e-b432-b5a49afb1e86",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/advertisement/get")
            .post("https://api2.mubu.com/v3/api/advertisement/get")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "10",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "ab234a98-f611-4f9c-a66a-c8c39b700622",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "30",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "37ca5869-a410-4fa9-89a4-e0fbdd084545",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .post("https://api2.mubu.com/v3/api/list/create_doc")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "25",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "6a092679-4bed-4bc9-8061-010c67f07af5",
                }
            )
            .with_json({"folderId": "0", "type": 0})
            .extract()
            .with_jmespath("body.data.id", "documentId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "30",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "f031cd7c-86d4-4f0f-b71e-5c2a8fa5c0e0",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .post("https://api2.mubu.com/v3/api/user/current_level")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "29",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "26484f28-5494-4d74-9f50-3adcbe2e043b",
                }
            )
            .with_json({"document_id": "${documentId}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .post("https://api2.mubu.com/v3/api/document/edit/get")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "37",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "9cd055cb-d241-4ae1-b426-b4a84ae8e573",
                }
            )
            .with_json({"docId": "${documentId}", "password": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/doc/list")
            .post("https://api2.mubu.com/v3/api/refer/doc/list")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "29",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "x-request-id": "14d2c823-f348-4889-9131-89e84c91cbab",
                }
            )
            .with_json({"targetDocId": "${documentId}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_invite_count")
            .get("https://api2.mubu.com/v3/api/user/get_invite_count")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "1700f1d3-56ea-42e9-8c29-74515221639f",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("https://api2.mubu.com/v3/api/colla/register")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "x-request-id": "65fa715b-e1ea-44e2-a966-7a9ad7ebc232",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .options("https://api2.mubu.com/v3/api/colla/members")
            .with_params(
                **{"documentId": "${documentId}", "memberId": "6646311528456261"}
            )
            .with_headers(
                **{
                    "accept": "*/*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "access-control-request-headers": "data-unique-id,jwt-token,request-id,x-request-id",
                    "access-control-request-method": "GET",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .get("https://api2.mubu.com/v3/api/colla/members")
            .with_params(
                **{"documentId": "${documentId}", "memberId": "6646311528456261"}
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "request-id": "members:6646311528456261:1610268780515",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "x-request-id": "28a45218-c628-479d-b3e0-85560b16a2c6",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "363",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "member-id": "6646311528456261",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "request-id": "MESSAGE:9564913:6646311528456261:4",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "58088de0-fb28-4646-94a0-3b61f02d4a98",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "2.0.0.553",
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {"name": "nameChanged", "original": "", "title": "德玛，"}
                            ],
                            "documentId": "${documentId}",
                            "type": "CHANGE",
                            "version": 0,
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 4,
                    "requestId": "MESSAGE:9564913:6646311528456261:4",
                    "token": "${documentId}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "609",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "member-id": "6646311528456261",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "request-id": "MESSAGE:9564913:6646311528456261:5",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "2446123c-2b79-45ee-b990-9a2a3cd39086",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "2.0.0.553",
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {
                                    "name": "nameChanged",
                                    "original": "德玛，",
                                    "title": "德玛，",
                                },
                                {
                                    "name": "nameChanged",
                                    "original": "德玛，",
                                    "title": "德玛，",
                                },
                                {
                                    "name": "nameChanged",
                                    "original": "德玛，",
                                    "title": "德玛",
                                },
                                {"name": "nameChanged", "original": "德玛", "title": "德"},
                                {"name": "nameChanged", "original": "德", "title": ""},
                            ],
                            "documentId": "${documentId}",
                            "type": "CHANGE",
                            "version": 1,
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 5,
                    "requestId": "MESSAGE:9564913:6646311528456261:5",
                    "token": "${documentId}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .post("https://api2.mubu.com/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "57",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "x-request-id": "c5ddb0ec-5e19-4bb0-bb6a-1fe9dc649669",
                }
            )
            .with_json({"docId": "${documentId}", "keywords": "德玛，", "option": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "358",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "member-id": "6646311528456261",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "request-id": "MESSAGE:9564913:6646311528456261:7",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "5fce5550-ec22-44d6-9798-8ad1ce7cb66b",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "2.0.0.553",
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {"name": "nameChanged", "original": "", "title": "demo"}
                            ],
                            "documentId": "${documentId}",
                            "type": "CHANGE",
                            "version": 2,
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 7,
                    "requestId": "MESSAGE:9564913:6646311528456261:7",
                    "token": "${documentId}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "516",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "member-id": "6646311528456261",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "request-id": "MESSAGE:9564913:6646311528456261:9",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "08c9b63d-8c43-4b65-a8e5-270b2ed635e8",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "2.0.0.553",
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {
                                    "name": "nameChanged",
                                    "original": "demo",
                                    "title": "demo2",
                                },
                                {
                                    "created": [
                                        {
                                            "index": 0,
                                            "node": {
                                                "children": [],
                                                "id": "qfeEyBHc8n",
                                                "modified": 1610268787483,
                                                "text": "",
                                            },
                                            "parentId": None,
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                    "name": "create",
                                },
                            ],
                            "documentId": "${documentId}",
                            "type": "CHANGE",
                            "version": 3,
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 9,
                    "requestId": "MESSAGE:9564913:6646311528456261:9",
                    "token": "${documentId}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .post("https://api2.mubu.com/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "53",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "x-request-id": "e976a316-8d4f-46f2-9e78-904495c0154c",
                }
            )
            .with_json({"docId": "${documentId}", "keywords": "demo2", "option": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "657",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "member-id": "6646311528456261",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "request-id": "MESSAGE:9564913:6646311528456261:11",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "eee66d2f-8639-4f2f-ab49-6c0637f9f1b8",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "2.0.0.553",
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "original": {
                                                "id": "qfeEyBHc8n",
                                                "modified": 1610268787483,
                                                "text": "",
                                            },
                                            "path": ["nodes", 0],
                                            "updated": {
                                                "id": "qfeEyBHc8n",
                                                "modified": 1610268789083,
                                                "text": "<span>1</span>",
                                            },
                                        }
                                    ],
                                },
                                {
                                    "created": [
                                        {
                                            "index": 1,
                                            "node": {
                                                "children": [],
                                                "id": "6QtkZUAEhW",
                                                "modified": 1610268789273,
                                                "text": "",
                                            },
                                            "parentId": None,
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                    "name": "create",
                                },
                            ],
                            "documentId": "${documentId}",
                            "type": "CHANGE",
                            "version": 4,
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 11,
                    "requestId": "MESSAGE:9564913:6646311528456261:11",
                    "token": "${documentId}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "657",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "member-id": "6646311528456261",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "request-id": "MESSAGE:9564913:6646311528456261:13",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "509b528d-c5b1-4935-a5f2-984f2881d9ca",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "2.0.0.553",
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "original": {
                                                "id": "6QtkZUAEhW",
                                                "modified": 1610268789273,
                                                "text": "",
                                            },
                                            "path": ["nodes", 1],
                                            "updated": {
                                                "id": "6QtkZUAEhW",
                                                "modified": 1610268790251,
                                                "text": "<span>3</span>",
                                            },
                                        }
                                    ],
                                },
                                {
                                    "created": [
                                        {
                                            "index": 2,
                                            "node": {
                                                "children": [],
                                                "id": "bNbTGgcoUN",
                                                "modified": 1610268790409,
                                                "text": "",
                                            },
                                            "parentId": None,
                                            "path": ["nodes", 2],
                                        }
                                    ],
                                    "name": "create",
                                },
                            ],
                            "documentId": "${documentId}",
                            "type": "CHANGE",
                            "version": 5,
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 13,
                    "requestId": "MESSAGE:9564913:6646311528456261:13",
                    "token": "${documentId}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "504",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "member-id": "6646311528456261",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "request-id": "MESSAGE:9564913:6646311528456261:15",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "46e66fa0-206d-4e6b-b958-f1aa11febc3d",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "2.0.0.553",
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "original": {
                                                "id": "bNbTGgcoUN",
                                                "modified": 1610268790409,
                                                "text": "",
                                            },
                                            "path": ["nodes", 2],
                                            "updated": {
                                                "id": "bNbTGgcoUN",
                                                "modified": 1610268791292,
                                                "text": "<span>5</span>",
                                            },
                                        }
                                    ],
                                }
                            ],
                            "documentId": "${documentId}",
                            "type": "CHANGE",
                            "version": 6,
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 15,
                    "requestId": "MESSAGE:9564913:6646311528456261:15",
                    "token": "${documentId}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "461",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "member-id": "6646311528456261",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "request-id": "MESSAGE:9564913:6646311528456261:16",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "201ac65c-6072-4986-9b99-c62000733b05",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "2.0.0.553",
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {
                                    "created": [
                                        {
                                            "index": 3,
                                            "node": {
                                                "children": [],
                                                "id": "JxG3xETMql",
                                                "modified": 1610268791449,
                                                "text": "",
                                            },
                                            "parentId": None,
                                            "path": ["nodes", 3],
                                        }
                                    ],
                                    "name": "create",
                                }
                            ],
                            "documentId": "${documentId}",
                            "type": "CHANGE",
                            "version": 7,
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 16,
                    "requestId": "MESSAGE:9564913:6646311528456261:16",
                    "token": "${documentId}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "504",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "member-id": "6646311528456261",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "request-id": "MESSAGE:9564913:6646311528456261:18",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "6a7cbca8-4559-43b0-a343-b192d2bb80c6",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "2.0.0.553",
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "original": {
                                                "id": "JxG3xETMql",
                                                "modified": 1610268791449,
                                                "text": "",
                                            },
                                            "path": ["nodes", 3],
                                            "updated": {
                                                "id": "JxG3xETMql",
                                                "modified": 1610268792900,
                                                "text": "<span>6</span>",
                                            },
                                        }
                                    ],
                                }
                            ],
                            "documentId": "${documentId}",
                            "type": "CHANGE",
                            "version": 8,
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 18,
                    "requestId": "MESSAGE:9564913:6646311528456261:18",
                    "token": "${documentId}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/batch_delete")
            .post("https://api2.mubu.com/v3/api/list/batch_delete")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "37",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "0ab1e930-5321-11eb-a1bd-ad0c581d182d",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTU2NDkxMyIsImV4cCI6MTYxMjg2MDc3MCwiaWF0IjoxNjEwMjY4NzcwfQ.69kT7kwvkk5WkDDBYVFw81c1tnFpA7UCy6WPji5McJPuT0hfK1L-uwkMIcYMzUTUWfBc534pntZSntsoVx5pBg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "version": "3.0.0",
                    "x-request-id": "6e359fc7-2b95-48e7-a418-80907c5fb860",
                }
            )
            .with_json({"docs": ["37dJLmYwNJh"], "folders": []})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuLoginCreateDoc().test_start()
